In [2]:
import numpy as np
from numpy.random import PCG64 as pcg
from numpy.random import Generator as gen

In [8]:
gen(pcg()).normal(loc=5, scale=2,size=(3,3))

array([[ 3.13663237,  6.37896649,  6.09650336],
       [ 4.56498378,  7.0225757 ,  8.38795342],
       [ 1.84816358, -2.05704945,  5.27767457]])

In [50]:
# if a given seed, we need to run pcg(seed=x) every time
u = gen(pcg(seed=40)).uniform(size=(3,3)) * 100 # between (0.0,1.0) by default you can change it
r = gen(pcg(seed=40)).random(size=(3,3)) * 100 # between (0.0,1.0)
n = gen(pcg(seed=40)).normal(loc=5, scale=2, size=(3,3)) # mean = 5, deviation = 2
# given n-choices each one with p probability (default is same p for all) create a matrix
c = gen(pcg(seed=40)).choice([1,2,3,4,5],p=(0.1,0.1,0.2,0.3,0.3),size=(3,3))
# PMF = (e^-lam)*(lam^k)/k!, prob of observing k-events given an average of lam-events (call center - calls/hour)
p = gen(pcg(seed=40)).poisson(lam = 10,size=(5,5))
# out of n-events given a p-probability how many events returns
b = gen(pcg(seed=40)).binomial(n= 100, p= 0.3,size=(5,5))
l = gen(pcg(seed=40)).logistic(loc = 9,size=(5,5))

In [51]:
samples = {'uniform * 100':u,'random * 100':r,'normal':n,'choice':c,'poisson':p, 'binomial' : b}
[print("{}:\n {}".format(k,samples[k])) for k in samples.keys()]

uniform * 100:
 [[72.98984953 69.34149568 94.19210172]
 [ 5.965206   69.05209707 92.2397519 ]
 [47.56831775 33.8390691  60.18828053]]
random * 100:
 [[72.98984953 69.34149568 94.19210172]
 [ 5.965206   69.05209707 92.2397519 ]
 [47.56831775 33.8390691  60.18828053]]
normal:
 [[2.71581539 2.86132684 3.48548499]
 [6.53731626 2.92412907 2.94792733]
 [4.21476148 7.77545789 3.16509808]]
choice:
 [[5 4 5]
 [1 4 5]
 [4 3 4]]
poisson:
 [[12 16 10 11  5]
 [11  3  7 13  6]
 [10  9  9 11  9]
 [ 8  7  7 12 11]
 [ 7  8  5 11  9]]
binomial:
 [[33 32 37 23 32]
 [37 30 28 31 33]
 [24 24 32 22 22]
 [28 26 33 34 26]
 [25 28 30 30 29]]


[None, None, None, None, None, None]

In [52]:
# poisson distribution
def PMF(mean_rate, kevents):
    return m.pow(m.e,-mean_rate)*m.pow(mean_rate,kevents)/m.factorial(kevents)
# example given avg of 10 events, if we check the probability of occurring 1 ... 20 events
# the sum of all probabilities should be close to 100%
lambda_events = 10
max_number_of_events = 20
print([PMF(lambda_events,i) for i in range(max_number_of_events)])
sum([PMF(lambda_events,i) for i in range(max_number_of_events)])    

[4.5399929762484875e-05, 0.00045399929762484877, 0.0022699964881242435, 0.007566654960414146, 0.018916637401035365, 0.03783327480207073, 0.06305545800345122, 0.09007922571921602, 0.11259903214902002, 0.12511003572113336, 0.12511003572113336, 0.11373639611012125, 0.09478033009176769, 0.07290794622443669, 0.05207710444602621, 0.034718069630684134, 0.021698793519177587, 0.01276399618775152, 0.0070911089931952895, 0.003732162627997521]


0.9965456580241434