In [1]:
import numpy as np
import math

In [60]:
# helper for formatting
def array2floatstr(nparray):
    temp = nparray.copy()
    if not('float' in temp.dtype.__str__()):
        temp = np.array(nparray,dtype='float')
    return np.array2string(temp,formatter={'float_kind': lambda x: '%.2f' % x})    

In [2]:
a = np.random.normal(5.0,2.0,size=(3,3))

In [3]:
aui32 = np.array(a,dtype="uint32")

In [4]:
aui32

array([[5, 6, 3],
       [5, 2, 6],
       [4, 5, 7]], dtype=uint32)

In [5]:
# by default reduce apply minimum on the axis=0 (columns)
np.minimum.reduce(aui32)

array([4, 2, 3], dtype=uint32)

In [6]:
# calling min directly does the same as above
np.min(aui32,axis=0)

array([4, 2, 3], dtype=uint32)

In [7]:
# percentile display
sorted_aui32 = np.sort(aui32,axis=None)
perc_value = 50
perc_index = float(sorted_aui32.size) * (float(perc_value) / 100.0)
perc_index_ui32 = int(round(perc_index + 0.5)) - 1 # base 0
dummy_list = ['-'] * sorted_aui32.size
dummy_list[perc_index_ui32] = '*'
print('Percentile {} at index {} with value {} (* sorted array)'.format(perc_value,perc_index_ui32 + 1,sorted_aui32[perc_index_ui32 ]))
print(np.array(sorted_aui32,dtype='str').tolist())
print(dummy_list)
result_np_perc = np.percentile(aui32, perc_value, interpolation = "nearest")
# quan does the same as perc but parameter passed is [0,1] instead of [0,100]
result_np_quan = np.quantile(aui32, float(perc_value) / 100.0, interpolation = "nearest")
print('np perc result {}'.format(result_np_perc))
print('np quan result {}'.format(result_np_quan))

Percentile 50 at index 5 with value 5 (* sorted array)
['2', '3', '4', '5', '5', '5', '6', '6', '7']
['-', '-', '-', '-', '*', '-', '-', '-', '-']
np perc result 5
np quan result 5


In [23]:
# mean, average
# the only difference is that average func can take a weights array 
aui32_mean = np.mean(aui32)
aui32_avg = np.average(aui32)
arr_weights = np.random.random(size=aui32.shape)
aui32_weighted_avg = np.average(aui32, weights=arr_weights)
print('Mean         : {}'.format(aui32_mean))
print('Avg          : {}'.format(aui32_avg))
print('Avg Weighted : {}'.format(aui32_weighted_avg))
print('(using random weights array)')
print('{}'.format(array2floatstr(arr_weights)))

Mean         : 4.777777777777778
Avg          : 4.777777777777778
Avg Weighted : 5.331106493866634
(using random weights array)
[[0.85 0.55 0.02]
 [0.64 0.28 0.16]
 [0.04 0.83 0.80]]


In [35]:
# variance, std
np_var = np.var(aui32)
np_std = np.std(aui32)
# for illustration purposes, manual calculation variance: SUM(E( (mean - val) ^ 2)) / num_elements
print('Manual variance each element:')
print('\t {}'.format(array2floatstr(np.array(sorted_aui32,dtype='float'))))
print('\t-{}'.format(array2floatstr(np.array([aui32_mean] * sorted_aui32.size))))
temp = [math.pow(e - aui32_mean,2) for e in sorted_aui32]
print('\t^2%s' % ('-' * 50))
print('\t %s' % array2floatstr(np.array(temp)))
print('Manual variance : {}'.format(sum(temp)/sorted_aui32.size))
print('Source array')
print(aui32)
print('Sorted')
print(sorted_aui32)
print('Variance    : {}'.format(np_var))
print('Std Var     : {}'.format(np_std))
print('std^2 = var : {}'.format(math.pow(np_std,2)))

Manual variance each element:
	 [2.00 3.00 4.00 5.00 5.00 5.00 6.00 6.00 7.00]
	-[4.78 4.78 4.78 4.78 4.78 4.78 4.78 4.78 4.78]
	^2--------------------------------------------------
	 [7.72 3.16 0.60 0.05 0.05 0.05 1.49 1.49 4.94]
Manual variance : 2.17283950617284
Source array
[[5 6 3]
 [5 2 6]
 [4 5 7]]
Sorted
[2 3 4 5 5 5 6 6 7]
Variance    : 2.17283950617284
Std Var     : 1.4740554623801778
std^2 = var : 2.17283950617284


In [131]:
# covariance
np_cov = np.cov(aui32)
print(array2floatstr(aui32))
print(array2floatstr(np_cov))
num_rows = aui32.shape[0]
mul_aui32_OneOverRows = aui32 * (1.0 / num_rows)
ones_matrix = np.ones([num_rows] * 2)
m_deviations = aui32 - np.dot(ones_matrix, mul_aui32_OneOverRows)
print('D = X - 1 * 1\' * X * (1/r)')
print('Ones matrix:\n %s' % ones_matrix)
print('aui32 * 1/r: \n%s' % mul_aui32_OneOverRows)
print('Result (X - (1 * 1\' * X * 1/r))):\n:%s' % m_deviations)
# np.corrcoef(aui32)

[[5.00 6.00 3.00]
 [5.00 2.00 6.00]
 [4.00 5.00 7.00]]
[[2.33 -2.83 -1.83]
 [-2.83 4.33 1.33]
 [-1.83 1.33 2.33]]
D = X - 1 * 1' * X * (1/r)
Ones matrix:
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
aui32 * 1/r: 
[[1.66666667 2.         1.        ]
 [1.66666667 0.66666667 2.        ]
 [1.33333333 1.66666667 2.33333333]]
Result (X - (1 * 1' * X * 1/r))):
:[[ 0.33333333  1.66666667 -2.33333333]
 [ 0.33333333 -2.33333333  0.66666667]
 [-0.66666667  0.66666667  1.66666667]]
